name: Playwright Tests with Allure and HTML Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests with Allure and HTML report
      run: npx playwright test --reporter=line,allure-playwright,html

    - name: Generate Allure Report
      run: |
        rm -rf allure-report
        npx allure generate allure-results -o allure-report

    - name: Upload Playwright HTML Report (Artifact)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload Allure Report (Artifact)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30

    # OPTIONAL - Deploy Allure Report to GitHub Pages (for public viewing)
    - name: Deploy Allure Report to GitHub Pages
      run: |
        if [ -d "allure-report" ]; then
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions@github.com"
          
          # Reset nhánh gh-pages tránh lỗi checkout
          git fetch origin gh-pages || git checkout --orphan gh-pages
          git checkout gh-pages || git checkout --orphan gh-pages
          
          # Xóa nội dung cũ để tránh file lỗi
          git rm -rf . > /dev/null 2>&1
          
          # Copy báo cáo mới
          cp -r allure-report/* .
          
          # Đẩy lên GitHub Pages
          git add .
          git commit -m "Update Allure Report" || echo "No changes to commit"
          git push origin gh-pages --force
        else
          echo "⚠️ No allure-report generated, skipping deployment."
        fi
