name: Playwright Tests with Allure and HTML Report

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests with Allure and HTML report
      run: npx playwright test --reporter=line,allure-playwright,html

    - name: Generate Allure Report
      run: |
        npx allure generate allure-results --clean -o allure-report

    - name: Upload Playwright HTML Report (Artifact)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

    - name: Upload Allure Report (Artifact)
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-report
        path: allure-report/
        retention-days: 30

    # OPTIONAL - Deploy Allure Report to GitHub Pages (for public viewing)
    - name: Deploy Allure Report to GitHub Pages
      if: success() || failure()
      run: |
        git config --global user.email "github-actions@github.com"
        git config --global user.name "github-actions"

        git fetch

        # Tạo branch gh-pages nếu chưa có
        if ! git ls-remote --exit-code --heads origin gh-pages; then
          git checkout --orphan gh-pages
          touch .keep
          git add .keep
          git commit -m "Init gh-pages branch"
          git push origin gh-pages
        else
          git checkout gh-pages
        fi

        # Copy report nếu có
        if [ -d "allure-report" ]; then
          rm -rf *
          cp -r allure-report/* .
          git add .
          git commit -m "Update Allure Report - $(date)" || true
          git push origin gh-pages
        else
          echo "❌ Không tìm thấy allure-report, bỏ qua deploy."
        fi